name: "Meeting Topic"
description: "Propose a topic or update for an upcoming meeting"
title: "Topic: <Short Title>"
labels: [meeting-topic]
body:
  - type: input
    id: owner
    attributes:
      label: Owner (GitHub handle)
      placeholder: "@username"
  - type: textarea
    id: context
    attributes:
      label: Context
      description: 1–3 sentences
  - type: textarea
    id: materials
    attributes:
      label: Links to materials
      description: slides, notebooks, PRs

